[package]
name = "mae-repo_macro"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
proc-macro=true


[dependencies]
chrono = "0.4.41"
proc-macro2 = "1.0.95"
quote = "1.0.40"
serde_json = "1.0.140"
syn = { version = "2.0.104", features = ["extra-traits"] }
