# deny.toml: Workspace-wide dependency policy enforcement
#  To add license exceptions, create a file cwd/deny.exceptions.toml and add them there.

[licenses]
unused-allowed-license= "allow"
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-3.0",
    "ISC",
    "LicenseRef-Proprietary",
    "MPL-2.0",
    "Zlib"
]

[advisories]
unmaintained = "workspace"

[bans]
multiple-versions="allow"

[sources]
unused-allowed-source = "allow"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
private = ["https://github.com/MrCartaaa"]
